version: "3.8"

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Map host port to container port
    container_name: angular-nginx

    networks:
      - app-app-network
 
networks:
  app-app-network:
    driver: bridge