services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:8080"  # Map host port to container port
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"  # Map host port to container port
    # volumes:
      # - .nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
